name: My Workflow

on: [push]

jobs:
  myJob:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2


    - name: Use My Custom Action
      id: mycustomaction
      uses: ./.github/actions/custom-name-action
      with:
        myInput: 'Mohamed'

    - name: Print Output
      run: echo  ${{ steps.mycustomaction.outputs.myOutput }}
